import express from "express";
import cors from "cors";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { createPublicClient, http, parseAbi, parseAbiItem } from "viem";
import { base } from "viem/chains";
import { Barretenberg, Fr } from "@aztec/bb.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ─── Initialize Barretenberg for Poseidon2 hashing ────────────
// bb.js poseidon2Hash is the ONLY correct Poseidon2 implementation
// that matches Noir's Poseidon2::hash and the on-chain LibPoseidon2.
// DO NOT use poseidon-lite — its "poseidon2" is original Poseidon with 2 inputs,
// which is a completely different hash function.
let bb: Barretenberg;

async function poseidon2Hash(left: bigint, right: bigint): Promise<bigint> {
  const result = await bb.poseidon2Hash([new Fr(left), new Fr(right)]);
  return BigInt(result.toString());
}

// ─── Configuration ────────────────────────────────────────────
const PORT = process.env.PORT || 3001;
const VENICE_API_KEY =
  process.env.VENICE_API_KEY ||
  "VENICE_INFERENCE_KEY_KGq6jatZVf4-daQeEzsDwilsVcnef8T0mC77mu7d3B";
const VENICE_BASE_URL =
  process.env.VENICE_BASE_URL || "https://api.venice.ai/api/v1";
const CONTRACT_ADDRESS = process.env.CONTRACT_ADDRESS as `0x${string}`;
const RPC_URL = process.env.RPC_URL || "https://mainnet.base.org";
const NULLIFIER_FILE = process.env.NULLIFIER_FILE || "./data/spent-nullifiers.json";

// Path to the circuit verification key (generated by bb)
const VK_PATH = path.resolve(
  __dirname,
  "../../circuits/target/vk"
);

// ─── On-Chain Root Verification ───────────────────────────────
const publicClient = createPublicClient({
  chain: base,
  transport: http(RPC_URL),
});

const API_CREDITS_ABI = parseAbi([
  "function getTreeData() view returns (uint256 size, uint256 depth, uint256 root)",
]);

let cachedRoot: string | null = null;
let cachedRootTimestamp = 0;
const ROOT_CACHE_TTL_MS = 5000; // 5 seconds

async function getOnChainRoot(): Promise<string | null> {
  const now = Date.now();
  if (cachedRoot !== null && now - cachedRootTimestamp < ROOT_CACHE_TTL_MS) {
    return cachedRoot;
  }
  try {
    const [, , root] = await publicClient.readContract({
      address: CONTRACT_ADDRESS,
      abi: API_CREDITS_ABI,
      functionName: "getTreeData",
    });
    cachedRoot = "0x" + root.toString(16).padStart(64, "0");
    cachedRootTimestamp = now;
    return cachedRoot;
  } catch {
    // Tree is empty or contract not deployed
    cachedRoot = null;
    cachedRootTimestamp = now;
    return null;
  }
}

// ─── Nullifier Persistence ────────────────────────────────────
function loadNullifiers(): Set<string> {
  try {
    fs.mkdirSync(path.dirname(NULLIFIER_FILE), { recursive: true });
    const data = JSON.parse(fs.readFileSync(NULLIFIER_FILE, "utf-8"));
    return new Set(data);
  } catch {
    return new Set();
  }
}

function saveNullifier(hash: string) {
  spentNullifiers.add(hash);
  fs.mkdirSync(path.dirname(NULLIFIER_FILE), { recursive: true });
  fs.writeFileSync(NULLIFIER_FILE, JSON.stringify([...spentNullifiers]));
}

const spentNullifiers = loadNullifiers();

// ─── Express App ──────────────────────────────────────────────
const app = express();
app.use(cors());
app.use(express.json({ limit: "1mb" }));

// Health check
app.get("/health", async (_req, res) => {
  const onChainRoot = await getOnChainRoot();
  res.json({
    status: "ok",
    spentNullifiers: spentNullifiers.size,
    onChainRoot,
  });
});

// Get server stats
app.get("/stats", async (_req, res) => {
  const onChainRoot = await getOnChainRoot();
  res.json({
    spentNullifiers: spentNullifiers.size,
    onChainRoot,
  });
});

// Check if a nullifier has been spent
app.get("/nullifier/:hash", (req, res) => {
  const spent = spentNullifiers.has(req.params.hash);
  res.json({ spent });
});

// ─── Circuit Artifact ──────────────────────────────────────────
// GET /circuit
// Returns the compiled Noir circuit JSON for client-side proof generation
app.get("/circuit", (_req, res) => {
  try {
    const circuitPath = path.resolve(__dirname, "../../circuits/target/circuits.json");
    const circuit = JSON.parse(fs.readFileSync(circuitPath, "utf-8"));
    res.setHeader("Access-Control-Allow-Origin", "*");
    res.json(circuit);
  } catch (err: any) {
    res.status(500).json({ error: "Circuit not found: " + err.message });
  }
});

// ─── Merkle Path for ZK Proof Generation ──────────────────────
// GET /merkle-path/:commitment
// Returns the Merkle sibling path for a given commitment (leaf value).
// Frontend needs this to generate ZK proofs.
app.get("/merkle-path/:commitment", async (req, res) => {
  try {
    const DEPTH = 16; // Circuit max depth

    // Read all CreditRegistered events from the contract to reconstruct the tree
    const events = await publicClient.getLogs({
      address: CONTRACT_ADDRESS,
      event: parseAbiItem(
        "event CreditRegistered(address indexed user, uint256 indexed index, uint256 commitment, uint256 newStakedBalance)"
      ),
      fromBlock: 0n,
    });

    if (events.length === 0) {
      res.status(404).json({ error: "No commitments registered yet" });
      return;
    }

    // Sort by index and extract commitment values
    const leaves = events
      .sort((a, b) => Number(a.args.index!) - Number(b.args.index!))
      .map((e) => e.args.commitment!);

    const targetCommitment = BigInt(req.params.commitment);
    const leafIndex = leaves.indexOf(targetCommitment);

    if (leafIndex === -1) {
      res.status(404).json({ error: "Commitment not found in tree" });
      return;
    }

    // Build the Merkle tree using bb.js Poseidon2 (matches Noir + on-chain LibPoseidon2).
    // We manually implement LeanIMT insertion since bb.js poseidon2Hash is async.
    const sideNodes: Record<number, bigint> = {};
    let treeDepth = 0;
    let treeSize = 0;

    // Track all node hashes at each level so we can extract sibling paths
    const levelNodes: Record<number, Record<number, bigint>> = {};

    for (const leaf of leaves) {
      const index = treeSize;
      if (2 ** treeDepth < index + 1) {
        treeDepth++;
      }

      let node = leaf;
      if (!levelNodes[0]) levelNodes[0] = {};
      levelNodes[0][index] = node;

      for (let level = 0; level < treeDepth; level++) {
        if (((index >> level) & 1) === 1) {
          node = await poseidon2Hash(sideNodes[level], node);
        } else {
          sideNodes[level] = node;
        }
        if (!levelNodes[level + 1]) levelNodes[level + 1] = {};
        levelNodes[level + 1][index >> (level + 1)] = node;
      }

      treeSize = index + 1;
      sideNodes[treeDepth] = node;
    }

    const treeRoot = sideNodes[treeDepth];

    // Now extract the sibling path for the target leaf.
    // For a LeanIMT, we need to reconstruct the full tree to get siblings.
    // Rebuild the tree level by level to get all intermediate nodes.
    const fullLevelNodes: Record<number, Record<number, bigint>> = { 0: {} };
    for (let i = 0; i < leaves.length; i++) {
      fullLevelNodes[0][i] = leaves[i];
    }

    for (let level = 0; level < treeDepth; level++) {
      const currentLevel = fullLevelNodes[level];
      if (!fullLevelNodes[level + 1]) fullLevelNodes[level + 1] = {};
      const numNodesAtLevel = Math.ceil(treeSize / (2 ** (level + 1)));
      for (let i = 0; i < numNodesAtLevel; i++) {
        const left = currentLevel[i * 2];
        const right = currentLevel[i * 2 + 1];
        if (left !== undefined && right !== undefined) {
          fullLevelNodes[level + 1][i] = await poseidon2Hash(left, right);
        } else if (left !== undefined) {
          // Odd node — promoted without hashing (LeanIMT behavior)
          fullLevelNodes[level + 1][i] = left;
        }
      }
    }

    // Extract sibling path
    const siblings: string[] = [];
    const indices: number[] = [];
    let currentIndex = leafIndex;

    for (let i = 0; i < DEPTH; i++) {
      if (i < treeDepth) {
        const siblingIndex = currentIndex ^ 1; // flip last bit to get sibling
        const sibling = fullLevelNodes[i]?.[siblingIndex];
        if (sibling !== undefined) {
          siblings.push(sibling.toString());
        } else {
          siblings.push("0");
        }
      } else {
        siblings.push("0");
      }
      indices.push((leafIndex >> i) & 1);
      currentIndex = currentIndex >> 1;
    }

    res.json({
      leafIndex,
      siblings,
      indices,
      root: treeRoot.toString(),
      depth: treeDepth,
    });
  } catch (err: any) {
    console.error("Merkle path error:", err);
    res.status(500).json({ error: err.message });
  }
});

/**
 * Main API endpoint — verify proof + proxy to Venice
 *
 * POST /v1/chat
 * {
 *   "proof": "<hex string>",
 *   "nullifier_hash": "0x...",
 *   "root": "0x...",
 *   "depth": 16,
 *   "messages": [{ "role": "user", "content": "..." }],
 *   "model": "llama-3.3-70b"
 * }
 */
app.post("/v1/chat", async (req, res) => {
  try {
    const { proof, nullifier_hash, root, depth, messages, model } = req.body;

    // ─── Input Validation ───────────────────────────────────
    if (!proof || !nullifier_hash || !root || depth === undefined || !messages) {
      res.status(400).json({
        error: "Missing required fields: proof, nullifier_hash, root, depth, messages",
      });
      return;
    }

    // ─── Check nullifier not already spent ──────────────────
    if (spentNullifiers.has(nullifier_hash)) {
      res.status(403).json({ error: "Nullifier already spent" });
      return;
    }

    // ─── Verify root matches on-chain state ─────────────────
    const onChainRoot = await getOnChainRoot();
    if (onChainRoot === null) {
      res.status(403).json({ error: "No commitments registered yet" });
      return;
    }
    if (root !== onChainRoot) {
      res.status(403).json({ error: "Invalid root — does not match on-chain state" });
      return;
    }

    // ─── Verify ZK proof ────────────────────────────────────
    try {
      const proofValid = await verifyProof(proof, nullifier_hash, root, depth);
      if (!proofValid) {
        res.status(403).json({ error: "Invalid proof" });
        return;
      }
    } catch (verifyError: any) {
      console.error("Proof verification error:", verifyError);
      res.status(403).json({
        error: "Proof verification failed",
        details: verifyError.message,
      });
      return;
    }

    // ─── Mark nullifier as spent BEFORE Venice call ─────────
    // This prevents race conditions — if two requests arrive
    // with the same nullifier simultaneously, only the first
    // one gets through.
    saveNullifier(nullifier_hash);

    // ─── Forward to Venice API ──────────────────────────────
    try {
      const veniceResponse = await fetch(
        `${VENICE_BASE_URL}/chat/completions`,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            Authorization: `Bearer ${VENICE_API_KEY}`,
          },
          body: JSON.stringify({
            model: model || "llama-3.3-70b",
            messages,
            stream: false,
          }),
        }
      );

      if (!veniceResponse.ok) {
        const errorText = await veniceResponse.text();
        console.error("Venice API error:", veniceResponse.status, errorText);
        // Don't unspend the nullifier — the credit is burned
        res.status(502).json({
          error: "Venice API error",
          status: veniceResponse.status,
        });
        return;
      }

      const veniceData = await veniceResponse.json();
      res.json(veniceData);
    } catch (veniceError: any) {
      console.error("Venice request failed:", veniceError);
      // Credit is burned even on Venice failure — this is the prepaid model
      res.status(502).json({
        error: "Failed to reach Venice API",
        details: veniceError.message,
      });
      return;
    }
  } catch (error: any) {
    console.error("Unexpected error:", error);
    res.status(500).json({ error: "Internal server error" });
  }
});

// ─── Proof Verification ───────────────────────────────────────
async function verifyProof(
  proofHex: string,
  nullifierHash: string,
  root: string,
  depth: number
): Promise<boolean> {
  try {
    // Dynamic import for bb.js (ESM)
    const { UltraHonkBackend } = await import("@aztec/bb.js");

    // Read the verification key
    const vkData = fs.readFileSync(VK_PATH);

    // Parse proof from hex
    const proofBytes = Buffer.from(
      proofHex.startsWith("0x") ? proofHex.slice(2) : proofHex,
      "hex"
    );

    // Public inputs: nullifier_hash, root, depth
    // These must match the order in the Noir circuit
    const publicInputs = [
      nullifierHash,
      root,
      "0x" + BigInt(depth).toString(16).padStart(64, "0"),
    ];

    // Load circuit artifact for verification
    const circuitPath = path.resolve(
      __dirname,
      "../../circuits/target/circuits.json"
    );
    const circuit = JSON.parse(fs.readFileSync(circuitPath, "utf-8"));

    const backend = new UltraHonkBackend(circuit.bytecode);

    // Reconstruct proof object
    const proof = {
      proof: proofBytes,
      publicInputs: publicInputs,
    };

    const valid = await backend.verifyProof(proof as any);
    return valid;
  } catch (error) {
    console.error("Proof verification error:", error);
    return false;
  }
}

// ─── Start Server ─────────────────────────────────────────────
async function start() {
  console.log("Initializing Barretenberg (Poseidon2 WASM)...");
  bb = await Barretenberg.new({ threads: 1 });
  console.log("Barretenberg ready.");

  app.listen(PORT, async () => {
    const onChainRoot = await getOnChainRoot();
    console.log(`\n🔐 ZK API Credits Server`);
    console.log(`   Port: ${PORT}`);
    console.log(`   Venice: ${VENICE_BASE_URL}`);
    console.log(`   VK: ${VK_PATH}`);
    console.log(`   Contract: ${CONTRACT_ADDRESS}`);
    console.log(`   RPC: ${RPC_URL}`);
    console.log(`   On-chain root: ${onChainRoot || "(no commitments yet)"}`);
    console.log(`   Loaded nullifiers: ${spentNullifiers.size}`);
    console.log(`   Nullifier file: ${NULLIFIER_FILE}`);
    console.log(`   Hash function: bb.js Poseidon2 (Noir-compatible)`);
    console.log(`\n   POST /v1/chat — Submit proof + get LLM response`);
    console.log(`   GET  /health  — Server health`);
    console.log(`   GET  /stats   — Spent nullifiers count`);
    console.log(`\n   No wallet. No API key. No identity.\n`);
  });
}

start().catch(console.error);
